/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ShoppingListRouteImport } from './routes/shopping-list'
import { Route as MealsRouteImport } from './routes/meals'
import { Route as IndexRouteImport } from './routes/index'

const ShoppingListRoute = ShoppingListRouteImport.update({
  id: '/shopping-list',
  path: '/shopping-list',
  getParentRoute: () => rootRouteImport,
} as any)
const MealsRoute = MealsRouteImport.update({
  id: '/meals',
  path: '/meals',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/meals': typeof MealsRoute
  '/shopping-list': typeof ShoppingListRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/meals': typeof MealsRoute
  '/shopping-list': typeof ShoppingListRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/meals': typeof MealsRoute
  '/shopping-list': typeof ShoppingListRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/meals' | '/shopping-list'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/meals' | '/shopping-list'
  id: '__root__' | '/' | '/meals' | '/shopping-list'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  MealsRoute: typeof MealsRoute
  ShoppingListRoute: typeof ShoppingListRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/shopping-list': {
      id: '/shopping-list'
      path: '/shopping-list'
      fullPath: '/shopping-list'
      preLoaderRoute: typeof ShoppingListRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/meals': {
      id: '/meals'
      path: '/meals'
      fullPath: '/meals'
      preLoaderRoute: typeof MealsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  MealsRoute: MealsRoute,
  ShoppingListRoute: ShoppingListRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
